// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// IStorageService is an autogenerated mock type for the IStorageService type
type IStorageService struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: image, path
func (_m *IStorageService) UploadImage(image *multipart.FileHeader, path string) error {
	ret := _m.Called(image, path)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, string) error); ok {
		r0 = rf(image, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIStorageService creates a new instance of IStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStorageService {
	mock := &IStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
